// Categories derived from WWO_CODE in chubin/wttr.in lib/constants.py
const WEATHER_CATEGORIES: Record<string, string> = {
  "113": "sunny",
  "116": "partly-cloudy",
  "119": "cloudy",
  "122": "very-cloudy",
  "143": "fog",
  "176": "light-showers",
  "179": "light-sleet-showers",
  "182": "light-sleet",
  "185": "light-sleet",
  "200": "thundery-showers",
  "227": "light-snow",
  "230": "heavy-snow",
  "248": "fog",
  "260": "fog",
  "263": "light-showers",
  "266": "light-rain",
  "281": "light-sleet",
  "284": "light-sleet",
  "293": "light-rain",
  "296": "light-rain",
  "299": "heavy-showers",
  "302": "heavy-rain",
  "305": "heavy-showers",
  "308": "heavy-rain",
  "311": "light-sleet",
  "314": "light-sleet",
  "317": "light-sleet",
  "320": "light-snow",
  "323": "light-snow-showers",
  "326": "light-snow-showers",
  "329": "heavy-snow",
  "332": "heavy-snow",
  "335": "heavy-snow-showers",
  "338": "heavy-snow",
  "350": "light-sleet",
  "353": "light-showers",
  "356": "heavy-showers",
  "359": "heavy-rain",
  "362": "light-sleet-showers",
  "365": "light-sleet-showers",
  "368": "light-snow-showers",
  "371": "heavy-snow-showers",
  "374": "light-sleet-showers",
  "377": "light-sleet",
  "386": "thundery-showers",
  "389": "thundery-heavy-rain",
  "392": "thundery-snow-showers",
  "395": "heavy-snow-showers",
};

export default function weatherCategory(code: string): string {
  return WEATHER_CATEGORIES[code] ?? "unknown";
}
